importName = ['/Users/ningli/Desktop/input.txt'];
table = importdata(importName);
[m,n] = size(table);
x = table(1, :);
y1 = table(2, :);
% y2 = table(3, :);
figure;
% plot(x, y1, '-ro', x, y2, '-bx');
plot(x, y1, '-o');
title('IC vs N');
xlabel('N: number of queries');
ylabel('IC for each channel');
% legend('channel 0','channel 1');